### ISSUE TITLE
Kibana Dashboards

### ISSUE THREAD

**Issue by dougburks** [cisagov/Malcolm#19]
Hello,

Interesting project you've got here! :)

The Kibana dashboards look very similar to ours in Security Onion.  Is that where they came from?  If so, may I ask that you provide proper acknowledgement?

Thanks in advance for your consideration!

**Comment by mmguero** [comment]
Hey, Doug. Malcolm's Kibana dashboards were modeled after Security Onion's but they were totally redone since the zeek log attribute names used by Moloch (which is what I'm normalizing all of our zeek logs to match) are named differently than the names used by Security Onion. But they are definitely inspired by and modeled after Security Onion, for sure, so I absolutely agree we should have an attribution in there. Would a mention in the README.md documentation suffice?

**Comment by mmguero** [comment]
What about, like:

> 
Many of Malcolm's prebuilt visualizations for Zeek logs are heavily inspired by the excellent [Kibana Dashboards](https://github.com/Security-Onion-Solutions/securityonion-elastic/tree/master/kibana/dashboards) that are part of [Security Onion](https://securityonion.net/).

Or is there some other wording you would prefer?

**Comment by mmguero** [comment]
By the way, I'm a big fan of your work. Security Onion is outstanding.

**Comment by dougburks** [comment]
Hey @mmguero ,

That wording sounds fine, thanks!

Perhaps there are other ways we can collaborate in the future.

Thanks!

**Comment by mmguero** [comment]
No problem, and I apologize for not having that in there originally. I totally agree! I've submitted a minor pull request or two to S.O. in the past (under a different GitHub handle) as I have used it in some analyst training I've done in another project. If I ever come up with any ways our projects can benefit each other I'll reach out. Cheers!
