### ISSUE TITLE
The readme content is all messed up

### ISSUE THREAD

**Issue by jmg-duarte** [cisagov/Malcolm#222]
# 🐛 Summary #

The readme content is all messed up
![image](https://user-images.githubusercontent.com/15343819/199946853-c0f0b21f-4db3-4e87-9d59-770c85fb1691.png)

**Comment by mmguero** [comment]
Ah, good catch. That stuff has to do with the GitHub Pages version of the documentation (see https://cisagov.github.io/Malcolm/), where it renders correctly because the mustache syntax is resolved, but not in GitHub. I'll have to figure out if there's a way to do it so that it renders correctly on both. I was trying to avoid hard-coding it for the sake of forks but I may have to.
