### ISSUE TITLE
Name attributes for page sections in documentation are broken 

### ISSUE THREAD

**Issue by meeas** [cisagov/Malcolm#255]
# 🐛 Summary #

You seem to be using `<a name="">` tags in your code to link to markdown sections.  None of these seem to be working (using the latest version of Chrome) on GitHub.  Indexes at the top of markdown pages do not take you to the subsections (tested on quickstart and Kubernetes pages), and links from other pages to subsections using `#` also fail.  However, the built-in markdown name attributes work fine.

I believe it is because you are using `name` instead of `id`, which was deprecated several years ago and finally dropped from browsers.  Personally, I think it is cleaner not to use the HTML snippets for id attributes and instead just use the auto-generated id attributes (which is markdown section name with spaces swapped for `-`).

## To reproduce ##

The following link takes me to the right page but does not scroll to the `#Future` section.

https://github.com/cisagov/Malcolm/blob/main/docs/kubernetes.md#Future

Looking in the source I can see the `# <a name="Future"></a> Future Enhancements`

## Expected behavior ##

The following modified link using the auto-generated markdown name attributes for sections works fine:

https://github.com/cisagov/Malcolm/blob/main/docs/kubernetes.md#-future-enhancements

Note: the only reason there is an extra `-` right after the `#` is because of the space between your name attributes and the section name.

**Comment by mmguero** [comment]
The markdown documentation, while readable on GitHub, is used with Jekyll to generate an HTML version of the documentation (see https://cisagov.github.io/Malcolm/docs/kubernetes.html, to use the example page you picked). That's why certain things in the markdown files themselves (those tags, apparently, and some other thing's you'll see with `{{ }}` replacers) look wrong in the markdown but end up working in the generated HTML version.

I'll look and see if I can get something that works for both browsing the documentation on GitHub and the jekyll target.

**Comment by mmguero** [comment]
As the main goal of the .md documentation is for rendering to HTML with GitHub pages, we're going to have to accept the minor inconvenience of the anchors working differently in the GitHub code previews. Leaving as-is for now.
