### ISSUE TITLE
Whether the suricata rule is triggered

### ISSUE THREAD

**Issue by gondmhd** [cisagov/Malcolm#261]
May I ask how to judge whether the suricata rule is triggered or not, and what circumstances will cause the suricata rule to fail to take effect? At some point, I found that the suricata event could not be viewed through the event provider in the dashboard.

**Comment by mmguero** [comment]
A few things you can check:

1. Go to the Discover app (e.g., https://<ip address>/dashboards/app/discover)
1. Set your time frame in the search bar to cover all of your data (e.g., set it to something like "15 years ago")
1. Add a query filter like: `event.provider:suricata`
1. Do you see any data? If so, then suricata is triggering. If not, then it's not.
1. If it's not, either a) your traffic isn't triggering suricata alerts because it doesn't match any of them, or b) you haven't enabled suricata to run. You could go through the [configuration](https://cisagov.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#MalcolmConfig) again and make sure you're answering "yes" for the questions related to capture for suricata.

**Comment by gondmhd** [comment]
My usage phenomenon is a bit strange. I uploaded a pcap package through malcolm. In the suricata container, I found the eve.json file under the /var/log/suricata path, which recorded some rule information that I triggered, but through https: ///dashboards/app/discover still can not find event.provider:suricata related information, the time range is large enough, and I have compared the suricata configuration on the server that normally displays the event.provider:suricata platform, and found that the configuration is the same
