### ISSUE TITLE
Scripts Start Error after full setup completed 

### ISSUE THREAD

**Issue by theusername-sudo** [cisagov/Malcolm#298]
# 🐛 Summary #

What's wrong? Please be specific.

## To reproduce ##

1. Run the ./scripts/configure
2. run the ./scripts/auth_setup
3. Error's out on ./scripts/start

## Expected behavior ##

What did you expect to happen that didn't?
I expected all the docker pods to start but i received 
"
ERROR: for DOCKERPODNAME  Cannot create container for service netbox-redis-cache: invalid JSON: json: cannot unmarshal number into Go struct field LogConfig.HostConfig.LogConfig.Config of type string " 

This happened on almost all of docker pods

**Comment by mmguero** [comment]
Could we get a bit more information?

* System (e.g., version of Linux or other platform you're trying to run on)
* `docker --version`
* `docker compose version` or `docker-compose version`

**Comment by theusername-sudo** [comment]
- system: ubuntu server 22.04 LTS (I can get more info if required) 
- docker version : 24.0.5, build 24.0.5-0ubuntu1~22.04.1
- docker-compose version: version 1.29.2, build unknown
- malcolm version - Malcolm v24.02.1 (is it an issue if I setup from this version)

**Comment by mmguero** [comment]
I'd be willing to bet the issue is the docker compose version. Looking at the [release log](https://docs.docker.com/compose/release-notes/), that version of compose is almost 3 years old. Which is interesting, considering your Docker version is less than a year old.

Any chance you could [update docker compose](https://docs.docker.com/compose/install/#scenario-two-install-the-compose-plugin) to a more up-to-date version and try?

**Comment by theusername-sudo** [comment]
That was exactly it, had to get it from the official repository instead of the one provided in ubuntu's default repo. Thank you so much!!!
