### ISSUE TITLE
Typo in documentation - live-analysis.md

### ISSUE THREAD

**Issue by un1c0rn-sec** [cisagov/Malcolm#302]
# 🐛 Summary #

There is a typo in https://github.com/cisagov/Malcolm/blob/main/docs/live-analysis.md

## To reproduce ##

1. Navigate to https://github.com/cisagov/Malcolm/blob/main/docs/live-analysis.md in a browser.
1. Note the line `generate and forward Zeek and Suricata logs, Arkime sessions, and other information to [Malcolm]({{ site.github.repository_url }})`

## Expected behavior ##

The word `Malcolm` in that line should be a proper hyperlink to its intended page.

## Any helpful log output or screenshots ##

None, it's pretty self-evident.

**Comment by un1c0rn-sec** [comment]
There is a similar issue on https://github.com/cisagov/Malcolm/blob/main/docs/malcolm-hedgehog-e2e-iso-install.md

**Comment by mmguero** [comment]
Those replacers inside of the mustache brackets (`{{ }}`) are intentional, as they are populated when the official HTML documentation is rendered. For example, [here's the page you listed.](https://cisagov.github.io/Malcolm/docs/live-analysis.html#LiveAnalysis).

When viewing them within the github repository tree, you are correct, you'll see the unresolved text. This is not a mistake, it's just not the documentation in its final form.

**Comment by un1c0rn-sec** [comment]
Oh, thank you for the clarification. My mistake.
