### ISSUE TITLE
Restart Policy in docker-compose.yml file

### ISSUE THREAD

**Issue by Kush2000528** [cisagov/Malcolm#307]
# 💡 Summary #

What is the work, as a high-level summary?

## Motivation and context ##

Why does this work belong in this project?

This would be useful because...

## Implementation notes ##

Please provide details for implementation, such as:

- an example for how this would be used
- what this would look like
- how this would act
- any related work, including links to related issues

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Criterion

**Comment by Kush2000528** [comment]
![Screenshot 2024-04-25 134225](https://github.com/cisagov/Malcolm/assets/132539966/80adc2ea-e73f-4cbd-8597-d2086d3219cf)
![Screenshot 2024-04-25 134258](https://github.com/cisagov/Malcolm/assets/132539966/44b112eb-d0f7-4075-948a-8319b23cfd4c)

There Is Issue In docker-compose.yml file in my running container is health check is failed so my container is down so the restart policy set "no" so how  can I set my container into running state

**Comment by mmguero** [comment]
I'm not sure I understand your question completely, but during the [MAlcolm configuration](https://cisagov.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#MalcolmConfig) you are asked "**Restart Malcolm upon system or Docker daemon restart?**"

* This question allows users to configure Docker's [restart policy](https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy) for Malcolm (i.e., the behavior used to restart Malcolm should the system be shut down or rebooted, or should one of Malcolm's components crash). Possible options are:
  - no - do not automatically restart the container
  - on-failure - restart the container if it exits due to an error, which manifests as a non-zero exit code
  - always - always restart the container if it stops
  - unless-stopped - similar to always, except that when the container is stopped (manually or otherwise), it is not restarted even after Docker daemon restarts; this is usually a good choice

If the opensearch container is not staying up, that is almost always a resource issue. You've probably got it not assigned enough resources.

1. What is the amount of RAM on the system?
2. How much do you have assigned to opensearch?
    * `grep Xms ./config/*.env`
3. `./scripts/logs -s opensearch`
    * share the output of those logs

Malcolm recommends 32GB of system memory, with an absolute minimum of 16GB. Containers not staying up is usually the result of not having enough resources available.

**Comment by Kush2000528** [comment]
Thanks For Your Response My Second Question is Can You Define for me how much storage and memory or CPU I can give to the sensor my sensor is working properly without any lag and high utilization ?

**Comment by mmguero** [comment]
For Malcolm, minimum system memory is 16GB and 8 CPU cores, but recommended is 32GB memory and 16+ CPU cores. For Hedgehog linux (standalone network sensor) minimum system memory is 8GB and 4 CPU cores, but recommended is 16GB and 8+ cores.

**Comment by Kush2000528** [comment]
Can You Define for Me Which Is the Best Opensource Monitoring Tool for docker containers?

**Comment by mmguero** [comment]
I don't have much of an opinion on monitoring tools. I know prometheus combined with grafana is popular. I suggest you google some and test some out and find which ones work for you.
