### ISSUE TITLE
502 Bad Gateways - nginx upstream error

### ISSUE THREAD

**Issue by staceinvader** [cisagov/Malcolm#37]
Hi, 

I'm unable to connect to any of the interfaces.

I'm getting the following error: 

nginx-proxy_1    | nginx: [emerg] host not found in upstream "moloch:8005" in /etc/nginx/nginx.conf:22
nginx-proxy_1    | nginx.1    | 2019/07/17 13:41:39 [error] 41#41: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.132, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:8005/", host: "192.168.1.85"

I believe this may be something to do with the fact that I'm not actually accessing the interface on the localhost, but from a bridged host elsewhere.

I've tried accessing /etc/nginx/nginx.conf but the directory doesnt exist? 

Thanks

**Comment by mmguero** [comment]
The nginx.conf file is inside the nginx container.

Usually, though, the issue with 502 errors is that one or more containers failed to start completely. If you run `docker ps -a` you should see a list of the docker containers of Malcolm. If any of them have `Exited` for the status rather than running, then those containers won't be available for nginx to proxy the connections to. In that case, run `docker-compose logs xxxxxx` and find the output of the container that exited prematurely.

It could be a resources issue: how much memory does the system have? How much have you allocated for Malcolm? You can run `./scripts/install.py -c` to reconfigure the docker-compose.yml parameters dealing with memory allocation, for Elasticsearch and Logstash in particular. You should also run `./scripts/wipe.sh` to reset everything to a clean state afterwards.

**Comment by staceinvader** [comment]
> The nginx.conf file is inside the nginx container.
> 
> Usually, though, the issue with 502 errors is that one or more containers failed to start completely. If you run `docker ps -a` you should see a list of the docker containers of Malcolm. If any of them have `Exited` for the status rather than running, then those containers won't be available for nginx to proxy the connections to. In that case, run `docker-compose logs xxxxxx` and find the output of the container that exited prematurely.
> 
> It could be a resources issue: how much memory does the system have? How much have you allocated for Malcolm? You can run `./scripts/install.py -c` to reconfigure the docker-compose.yml parameters dealing with memory allocation, for Elasticsearch and Logstash in particular. You should also run `./scripts/wipe.sh` to reset everything to a clean state afterwards.

Hey there, 

Thanks for the reply. Looks like I was being a complete idiot and only assigning the box 4gb RAM and configuring it to need 6.5gb. Sorry for the time waste!

Cheers
