### ISSUE TITLE
opensearch.keystore not created

### ISSUE THREAD

**Issue by jvlavl** [cisagov/Malcolm#514]
**Describe the bug**
the opensearch.keystore isn't created

Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/analist/Malcolm/opensearch/opensearch.keystore

If applicable, attach screenshots or container logs (e.g., the relevant bits of `./scripts/logs`) to help explain your problem.

**Malcolm Version:**
 - Version [ v24.01.0]

**How are you running Malcolm?**
- [ ] [ISO installed](https://cisagov.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#InstallationExample) (on VM or dedicated hardware)

**Additional context**

**Comment by mmguero** [comment]
You're using the startup script (`./scripts/start`) to run Malcolm, or the corresponding icons on the toolbar on the Malcolm install desktop, right? You're not trying to do `docker compose up` manually?

This should be created automatically on startup, so we need to determine why it's not happening. First, double-check and make sure the file doesn't exist incorrectly somehow (like with the wrong permissions, or as a directory, or something). Run `ls -l ./opensearch/opensearch.keystore` in your Malcolm installation directory. I assume this returns nothing? If it returns something, either a file with the wrong permissions, or an empty directory, or something else, use `sudo rm ./opensearch/opensearch.keystore` or `sudo rmdir ./opensearch/opensearch.keystore` to remove it before trying to start up.

If that doesn't fix the problem, we'll start with extra debugging turned on to figure out where the problem is. Run `./scripts/start -v`.

Pretty early on in the startup, you'll see something like this:

```
...
['docker', 'compose', '--profile', 'malcolm', '-f', '/home/analyst/Malcolm/docker-compose.yml', 'version']() returned 0: ['Docker Compose version v2.29.7', '']
Run profile (process.env): malcolm
['docker', 'compose', '--profile', 'malcolm', '-f', '/home/analyst/Malcolm/docker-compose.yml', 'ps', '-q', 'opensearch']() returned 0: []
['docker', 'run', '--rm', '--entrypoint', '/usr/local/bin/docker-uid-gid-setup.sh', '--env', 'PUID=1000', '--env', 'DEFAULT_UID=1000', '--env', 'PGID=1000', '--env', 'DEFAULT_GID=1000', '--env', 'PUSER_CHOWN=/usr/share/opensearch/config', '-v', '/home/analyst/Malcolm/opensearch:/usr/share/opensearch/config:rw', '-w', '/usr/share/opensearch/config', '-u', 'root', 'ghcr.io/idaholab/malcolm/opensearch:24.12.0', '/usr/share/opensearch/bin/opensearch-keystore', 'create']() returned 0: ['opensearch', 'uid=1000(opensearch) gid=1000(opensearch) groups=1000(opensearch)', 'Created opensearch keystore in /usr/share/opensearch/config/opensearch.keystore', '']
Ensuring "/home/tlacuache/devel/data/Malcolm/zeek/current" exists
Ensuring "/home/analyst/Malcolm/nginx/ca-trust" exists
Ensuring "/home/analyst/Malcolm/netbox/media" exists
...
```

So, a few lines before the "Ensuring ... exists" stuff, you'll see something about creating the opensearch.keystore file. Can you share that output?

**Comment by mmguero** [comment]
I'm going to convert this from an issue to a discussion in the Troubleshooting section.
